### ISSUE TITLE
Integration of 2nd order differential equation 

### ISSUE THREAD

**Issue by zweistein** [tbs1980/NumericalIntegration#6]
I would like to use this module to numerically integrate a second order differential equation, like:
`\ddot{x} =  P\cdot \dot{x} + Q\cdot x +R \cdot u` where, x and u are vectors and P, Q, R matrices. 
I want to integrate the `\ddot{x}` function, but the given example does not cover the case when there is a `\dot{x}` in the integral.

I can denote x1= x and x2 = \dot{x} so, I get a first order system, but then I'm going to have two parameters as input to the `IntegrandFunctor`.

Is this doable with the **NumericalIntegration** module? Can you point me to the good direction?
Thank you in advance.

**Comment by tbs1980** [comment]
Theoretically you can do this using our package. However, I highly recommend dedicated solvers for ODEs like [odeint](http://headmyshoulder.github.io/odeint-v2/index.html) or [sundials](https://computation.llnl.gov/casc/sundials/main.html). Hope this information helps.
