### ISSUE TITLE
Clarification of MPFR dependence

### ISSUE THREAD

**Issue by yixuan** [tbs1980/NumericalIntegration#7]
It seems that MPFR is actually **optional** rather than **required** if one only wants to use this library to calculate numerical integration instead of generating weights and abscissa (so that only `GaussKronrodNodesWeights.h` and `Integrator.h` are used).

Maybe it's better to explain this in README.

**Comment by mcsauder** [comment]
Hi yixuan,

Thanks so much for the feedback!  I've added a few lines to the readme to (hopefully) help clarify when multiprecision is required.  Please let me know if you think this helps, and let us know of any other improvements you think can be made as you discover them.  

We hope you find the library useful!

-mark

**Comment by yixuan** [comment]
Thank you for the great work! Just to let you know that I'm using **NumericalIntegration** in an R package (https://github.com/yixuan/RcppNumerical) of mine. Your library is very helpful. :smile:

**Comment by cxw42** [comment]
Thank you for releasing this library!  I am trying it out.  I see that CMakeLists.txt still shows MPFR, MPFRCPP, and GMP as `REQUIRED`.  From a few minutes of trying it out, it seems that MPFR is  required for the tests, but I can't tell if it is required for the code.  Is that indeed the case?  If so, should the CMakeLists.txt be updated?  Thanks for considering this question!
